AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket created by CloudFormation
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ansible-aws-cfn
      Tags:
        - Key: Project
          Value: ansible-aws-cfn
